### ISSUE TITLE
Max Number of plugs

### ISSUE THREAD

**Issue by mairbarg** [tnmendes/watt#3] opened 2020-01-02 20:53 UTC
I have 19 plugs in total, for some reason, there are only 16 plugs displayed.

**Comment by tnmendes** [comment] 2020-01-02 22:48
It is a limitation because of the initial design, to keep good ration between circles space the app was limited to 16 devices.

I am working now with version Watt 2.0 that will have a new concept that is multiple "spaces" where each space can have 16 devices, so it's going to be unlimited.

Here is a print screen of the new design:

![IMG-1966](https://user-images.githubusercontent.com/9822076/71698003-b8bbd400-2db1-11ea-8be2-1be63d127657.PNG)

**Comment by mairbarg** [comment] 2020-01-03 09:16
Thanks, will wait for this update. Do you have an ETA?

**Comment by tnmendes** [comment] 2020-01-03 22:18
Estimated time will be between 1-2 months.
@mairbarg do you want to be beta user of this app to test the new features?  If you are please share with me the email that you use with apple so I can invited you to testFlight.

**Comment by tnmendes** [comment] 2020-01-18 21:35
Version 2.0.0 will be released in the next few hours and with this, the problem is considered solved.

**Closed by tnmendes** 2020-01-18 21:35 UTC
Labels: bug
