### ISSUE TITLE
Kasa Matter Products

### ISSUE THREAD

**Issue by Chrishargrove58** [tnmendes/watt#123] opened 2023-08-20 09:20 UTC
Unable to connect to the new tp-link "matter" smart plugs on the app on iPhone IOS. Is that going to be a future feature or am I missing something?

**Comment by tnmendes** [comment] 2023-08-22 20:04
Hey @Chrishargrove58 can you tell me what matter device you have? Is the KP125M?

**Comment by UBNT-MikeTaylor** [comment] 2023-09-02 05:27
I have the same issue with KP125MP4(US).

**Comment by tnmendes** [comment] 2023-09-04 13:01
This plug is not for sale in Europe, so I'm still trying to understand how it works. From the YouTube videos I saw, you first need to add the Apple "Home" app and once there you can add the Tp-Link Kasa App, did you manage to add the Kasa app?

**Comment by nicgda** [comment] 2023-09-30 04:19
I have two KP125M. One is set in Homekit and the Kasa app. The other one is still in the box. I can do whatever test you need with it next week (October 2023).

**Comment by tnmendes** [comment] 2023-10-05 11:45
@nicgda Thank you for the offer of help, I will accept it. Could you send an email saying "hello" to this email address:
voless.app@gmail.com
So I can give you details on how you can help me!!!

**Comment by tnmendes** [comment] 2023-10-16 22:58
Hey guys, just one update. With the help of @nicgda , I was able to see how the new KP125M device is working, which is basically how Tapo brand devices work and also using the same servers. Possibly in the future, TP-Link will convert all devices to this form in order to unify Kasa and Tapo.

I now have to make some changes to how I have my code to work with KP125M, I'll try to finish it over the weekend

**Comment by tnmendes** [comment] 2023-11-06 19:20
Please try the new app 5.2.0 the new app supports the Kasa KP125M.
I am doing a small rollout of this app so it can take 7 days to be available for everyone, if you want to get the app now please go to the App Store and search for Watt for Smart Devices and the update will be available.

(after you update the Watt app, and open the app can take up to 8 minutes to be available KP125M reason is because of migration to the new system and I am just doing a full reload every 8 minutes )

**Comment by LeftcoastBBQ** [comment] 2023-11-08 16:41
My install of 5.2.0 still isn’t picking up the KP125M outlets.  Waited for far longer than 8 minutes (35 the first time), but still only the original number of plugs. 

Tried signing out (with the room re-creation that requires) as well as deleting the app and reinstalling after a phone reboot, but no difference. 

Anything I can do to help test?

**Comment by nicgda** [comment] 2023-11-08 17:05
I'm in the same situation with the KP125M on 5.2.0. I left the app in the foreground for over two hours on my iPad and tried the logout/login dance on my iPhone.
I have two KP125M also used with HomeKit, one just in the Kasa app and the one still available for testing (not on my account).

**Comment by tnmendes** [comment] 2023-11-12 00:41
I had a small problem migrating to the new system that support KP125M, I sent it to the Apple team for review 10 minutes ago a new app version. (It will probably take 48 hours to review and to be available on app store)

**Comment by nicgda** [comment] 2023-11-12 18:36
It's working with 5.2.1 👍

**Comment by LeftcoastBBQ** [comment] 2023-11-12 21:57
I can confirm as well!!  Awesome job, and scratch that one off the list.

**Comment by tnmendes** [comment] 2023-11-12 23:06
Thank you guys for reporting this problem and helping to test it.
A special thank you to @nicgda a for sharing access to KP125M plug with me.

I'm going to close this thread, if necessary it can be opened again

**Closed as completed by tnmendes** 2023-11-12 23:06 UTC
